### ISSUE TITLE
change the background color of search button (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/xplore#123]
# first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore

The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

## How you can help

At DAV we are currently re designing our branding. According to the new design we are changing the color scheme of all our applications including xplore. 

### The Issue

The task for this issue is to change the background color of the `search` button from 
![screen shot 2018-03-30 at 11 51 44 am](https://user-images.githubusercontent.com/2767425/38127007-b961358a-3411-11e8-985d-0e1d8e6e6a85.png)

to this...

![screen shot 2018-03-30 at 11 59 36 am](https://user-images.githubusercontent.com/2767425/38127027-db5552fc-3411-11e8-9b8f-5bad9d2fabe0.png)

You just need to change the `background color` in css for the search button

### Contributing to Xplore

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Xplore GitHub page](https://github.com/DAVFoundation/xplore) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/xplore](https://github.com/YOUR-USER-NAME/xplore)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network.

**Comment by vipulmahadik** [comment]
I can work on this as well :)

**Comment by cg-cnu** [comment]
Hey @vipulmahadik Thanks for your help! 
We create this first timer issues to help new contributors take their first steps in to open source with easy to solve issues. We feel creating this kind of issues will help them get used to the process of git, github and creating PR. Of course we can see that in the enthusiasm it gave you to contribute more to opensource. Lets leave this issue for some other first-timer. 

But, there is a little challenging task I just created. https://github.com/DAVFoundation/xplore/issues/129 This is also first timers but requires a bit of work. Would you like to give that a  shot ?

**Comment by vipulmahadik** [comment]
Sure, I can work on #129 !

**Comment by Roginkoshy** [comment]
I would like to work on this

**Comment by cg-cnu** [comment]
Go ahead @Roginkoshy 👍

**Comment by AnukrityJain** [comment]
I would want to try this

**Comment by cg-cnu** [comment]
Hey @AnukrityJain this is already claimed by @Roginkoshy Why don't you try https://github.com/DAVFoundation/xplore/issues/125

**Comment by cg-cnu** [comment]
Congratulations @Roginkoshy on your first open source contribution 👏 🍾 Hope you had fun and learned a few things in the process. Hope to see ya around. 😄
