### ISSUE TITLE
create Results container

### ISSUE THREAD

**Issue by debragail** [DAVFoundation/xplore#148]
Search results needs a results page.  Also clickable links in the headerSection like hash address in Transactions needs a way to be displayed.  suggesting a Results container that displays above Blocks and Account and below HeaderSection.

## Expected Behavior

Search query returns results in Results container.
Other clickable links can return results in container as needed.

## Current Behavior
There is no way to display search results and and there is no way to click addresses or hashes and display them.

## Possible Solution

Results container or new results page.

## Context

Needs design.

**Comment by debragail** [comment]
![results](https://user-images.githubusercontent.com/552529/50050704-e3a88c80-00b7-11e9-8ccd-71bbf5812258.png)

**Comment by TalAter** [comment]
Let's go with a simpler solution as described in https://github.com/DAVFoundation/DIPs/issues/3
