### ISSUE TITLE
Truncate address on mobile

### ISSUE THREAD

**Issue by debragail** [DAVFoundation/xplore#151]
On mobile the address needs to be truncated in order to fit.

## Expected Behavior

The address should look presentable, readable, and clickable.

## Current Behavior
Address overlaps with other text

## Possible Solution
Truncate when width is mobile 

## Steps to Reproduce (for bugs)
<img width="442" alt="screen shot 2018-12-15 at 22 59 20" src="https://user-images.githubusercontent.com/552529/50051000-ffaf2c80-00bd-11e9-9386-3b676e0523e7.png">
<img width="438" alt="screen shot 2018-12-15 at 22 58 58" src="https://user-images.githubusercontent.com/552529/50051001-05a50d80-00be-11e9-9635-381a1990c371.png">

1. Resize browser to mobile width or view on mobile

## Context
It's helpful to have the full address but also difficult to display on mobile or easily in all enviroments.
## Your Environment
Google Chrome Version 70.0.3538.110 (Official Build) (64-bit) Mac OSX Yoesmite

**Comment by TalAter** [comment]
`xplore` is a block explorer for blockchains that you run locally on your machine.

So when you're developing smart contracts, or developing with `dav-js`, and testing against a local Ethereum node running on your machine you have all the conveniences of a block explorer... this makes the scenario of someone running xplore on a mobile phone quite unlikely.

**Comment by debragail** [comment]
I thought this was going to be a public explorer on the website so was trying to make it responsive

**Comment by debragail** [comment]
https://coinsutra.com/blockchain-explorer/
