### ISSUE TITLE
Remove unnecessary return statement from accounts [first-timers-only]

### ISSUE THREAD

**Issue by griffobeid** [DAVFoundation/xplore#20]
## first-timers-only
This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more first-timers-only issues from DAV Foundation [here](https://github.com/DAVFoundation).

Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore
The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue
In the file `src/reducers/accounts.js` the arrow function can be simplified to return the value without the `return` statement. 

For example:  
`[getAccountsFulfilled]: (state, { payload }) => { return payload; }`
    
Can be simplified to:
`[getAccountsFulfilled]: (state, { payload }) => payload;`

### Contributing to Xplore
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ]  Comment in this issue that you would like to do it.
- [ ]  Open the Xplore GitHub page and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git
- [ ] Visit the [contributing guidelines](https://github.com/DAVFoundation/xplore/blob/master/CONTRIBUTING.md) for help getting started.
- [ ] Code, code, code...
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/xplore) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by THEozmic** [comment]
I would love to work on this

**Comment by griffobeid** [comment]
Thanks, @THEozmic :rocket: let me know if you have any questions. :octocat:

**Comment by THEozmic** [comment]
@griffobeid How can I be sure that my changes haven't broken anything seeing that there are no tests?

**Comment by griffobeid** [comment]
You could either write a test and open another pull request, or you can make sure the accounts section is being filled with data still in the block explorer dashboard.

**Comment by THEozmic** [comment]
There's still data in the accounts section and I'd like to setup the tests and probably write one that covers this case. I'm gonna raise a PR now.

**Comment by griffobeid** [comment]
Go for it! I recommend using jest.

**Comment by THEozmic** [comment]
I've been able to setup the test environment, should I go ahead and raise a PR? Or wait until this one: https://github.com/DAVFoundation/xplore/pull/24 has been merged?

**Comment by TalAter** [comment]
Wow @THEozmic ! What a spectacular 🌠  pull request.

I moved the tests to a new directory (to comply with the same standards we have in other projects). But other than that, well done 👍

I hope we can count on a many more contributions from you! I would love that.

**Comment by THEozmic** [comment]
Thank you @TalAter. I look forward to making more contributions

**Comment by TalAter** [comment]
@THEozmic Would you like to set up a similar structure for testing in one of our flagship projects - [missions](https://github.com/DAVFoundation/missions)?

This is a really cool one that we are now in the process of connecting to real drones for deliveries, to an autonomous boat, and to robots.

**Comment by THEozmic** [comment]
@TalAter Sure, I'd love to! I took a bit of a break this past weekend and will continue contributing this week. Expect that PR soon.
PS: I was already checking out missions and it looks amazing! The setup was pretty straightforward.

**Comment by TalAter** [comment]
@THEozmic Awesome! I created an issue for it: https://github.com/DAVFoundation/missions/issues/71
