### ISSUE TITLE
Remove unnecessary return statement from events [first-timers-only] 

### ISSUE THREAD

**Issue by griffobeid** [DAVFoundation/xplore#22]
## first-timers-only
This issue is tagged :octocat: first-timers-only. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more first-timers-only issues from DAV Foundation [here](https://github.com/DAVFoundation).

Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore
The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue
In the file `src/reducers/events.js` the arrow function can be simplified to return the value without the `return` statement. 

For example:  
`[getAccountsFulfilled]: (state, { payload }) => { return payload; }`
    
Can be simplified to:
`[getAccountsFulfilled]: (state, { payload }) => payload;`

### Contributing to Xplore
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ]  Comment in this issue that you would like to do it.
- [ ]  Open the Xplore GitHub page and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git
- [ ] Visit the [contributing guidelines](https://github.com/DAVFoundation/xplore/blob/master/CONTRIBUTING.md) for help getting started.
- [ ] Code, code, code...
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/xplore) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by felgeekpe** [comment]
i can take it!

**Comment by TalAter** [comment]
Go for it @felgeekpe 👍

**Comment by TalAter** [comment]
Looking good @felgeekpe 👍 

Thanks for the help, and congrats on making your first :octocat: pull request!
I hope it is the first of many.

**Comment by felgeekpe** [comment]
@TalAter Glad i can help! Thanks for the opportunity!
Just let me know if i can help with anything else

**Comment by TalAter** [comment]
Feel free to take any of the other non-first-timers-only issues 👍
