### ISSUE TITLE
Write a function getRpcServer that returns the RPC endpoint

### ISSUE THREAD

**Issue by griffobeid** [DAVFoundation/xplore#29]
Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore
The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue

Currently, there is an area to display the RPC Server in the app that is blank. A few things need to happen in order to display the RPC server in that box. First off we need to write a new function in the file `src/lib/blockchain.js` called `getRpcServer()` that returns the RPC endpoint. If you are confused about what RPC is have a look at this [stack exchange thread](https://ethereum.stackexchange.com/questions/10681/what-are-ipc-and-rpc). Also, I think that the [web3 documentation](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3versionnetwork) will be helpful. In particular, you should have a look at the `web3.currentProvider` function.

### Contributing to Xplore
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ]  Comment in this issue that you would like to do it.
- [ ]  Open the Xplore GitHub page and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git
- [ ] Visit the [contributing guidelines](https://github.com/DAVFoundation/xplore/blob/master/CONTRIBUTING.md) for help getting started.
- [ ] Code, code, code...
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/xplore) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by THEozmic** [comment]
I would love to have a go at this.

**Comment by griffobeid** [comment]
It's all yours @THEozmic! Thanks 😄

**Comment by THEozmic** [comment]
@griffobeid and @TalAter, here's what the block currently looks like. I need to know if I'm even displaying the right things:

![image](https://user-images.githubusercontent.com/15184445/36139726-fdb06fda-109e-11e8-9238-1c42cd5aaa3b.png)
 
Please, bear with me, it's my second time working with anything that has to do with blockchain. The first was creating bitcoin wallets.

And this is how I handled it in the reducer:

`import { getRpcServer } from '../actions';`

```
{
      title:'RPC Server',
      action:'getRpcServer',
      class:'rpc-server',
      icon:'rpc-server.png',
      tag:'rpcServer',
      value: getRpcServer().payload
},
```

**Comment by TalAter** [comment]
The image looks good.
I can check out the code when you send the pull request, better than seeing something out of context.
