### ISSUE TITLE
download and load bootstrap locally (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/xplore#65]
# first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore

The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue

The task for this issue is to get bootstrap locally so that we can use xplore offline. You can place the downloaded bootstrap file in `src/static/css/`

### Contributing to Xplore

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Xplore GitHub page](https://github.com/DAVFoundation/xplore) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git`
- [ ] **Edit the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/xplore](https://github.com/YOUR-USER-NAME/xplore)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by mariuslazar93** [comment]
Hey! I would like to help with this issue :) I have 2 questions though:

1. Does this issue include changing the path inside the `index.html` to point to the local version once it's downloaded?
2. Bootstrap is coming out of the box with `glyphicon` font, which also has to be downloaded locally. But I've seen you are using `font-awesome` too, so my question would be if you want both of them or just one? I can remove the `glyphicon` font from the local bootstrap file if you agree with this.

**Comment by cg-cnu** [comment]
Hey @mariuslazar93 Thanks for your help! 

1. Yes, you need to change the path in `index.html` as well
2. I would suggest keep the `glyphicon` fonts since we are still in the early development stage. @TalAter your thoughts ?

**Comment by TalAter** [comment]
Yeah, let's just keep it for now... the extra file size is a relatively minor concern as this isn't being served over the Internet.

**Comment by mariuslazar93** [comment]
Hi guys,

Would be good to have some installation guides for the project when run on Windows. I had encountered quite a few problems before I could actually run the project.

The main issue was around `node-gyp` package. In the end I found these [NodeJS Guidelines for Windows](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration) that helped me start the project in the end.

Anyway, was a fun experience! Thanks for the first PR opportunity!

**Comment by cg-cnu** [comment]
Hey @mariuslazar93 Thanks for your awesome work 👏 Sorry for the trouble on setting up the project on windows. Even I have faced few issues initially but later I moved on to mac. So, didn't have a breakdown of things to do. 

Would you mind jotting down all the steps you followed to get it working and add them to contributing.md ? That would be of great help to us because most of the core team is on mac. Let me know if you need any help on adding windows instructions to contributing.md 🙂  

Again, thank you for the pr and pointing out the issues on windows. ❤️  Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors/) to keep up to date with DAV development.

**Comment by mariuslazar93** [comment]
Hey @cg-cnu No worries! I have made the update on #91 PR :)
