### ISSUE TITLE
Add screenshot of Xplore to readme.md (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/xplore#69]
# first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore

The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue

The task for this issue is to add the screenshot of the application in `README.md`.
You can look at other DAV projects like `missions` for the location in readme. You can add the image to the project under `/src/images/`. 

### Contributing to Xplore

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Xplore GitHub page](https://github.com/DAVFoundation/xplore) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/xplore.git`
- [ ] **Edit the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/xplore](https://github.com/YOUR-USER-NAME/xplore)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by durgeshra** [comment]
I wish to contribute to this issue. :-)

**Comment by durgeshra** [comment]
I followed instructions in contributing.md, but I am unable to install dav-cli. Is there any other way to open the application to take screenshot?

**Comment by cg-cnu** [comment]
Hey @durgeshra Thanks for your interest in working on this issue. I would be happy to help! Would you mind sharing the exact error you got while running `dav-cli` 🙂

**Comment by durgeshra** [comment]
$ dav-cli -s
/usr/local/lib/node_modules/dav-cli/src/index.js:5
const { startTestnet } = require('./controllers/blockchain');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dav-cli/bin/dav-cli.js:5:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

This is the error I am getting. Actually, this crept in while I was trying to run dav-cli.

**Comment by mohinderps** [comment]
Hi @durgeshra, I followed the steps written in CONTRIBUTING.md and actually got everything up and running. I did not get this error.

**Comment by cg-cnu** [comment]
@durgeshra I haven't faced this issue... can you please share your node version and os, so that we can try debugging.

**Comment by tharun323** [comment]
i would like to work on this !

**Comment by cg-cnu** [comment]
Hey @mohinderps are you still interested in working on this one.

**Comment by mohinderps** [comment]
Yes @cg-cnu , I can work on this. But I have already submitted the PR for issue 67. So am I eligible to work on this?

**Comment by cg-cnu** [comment]
Hey @tharun323 would you like to give this a shot! 🙂

**Comment by mrcolo** [comment]
I would like to work on this too!

**Comment by mrcolo** [comment]
If this issue is already taken, is there anything else I can help y'all with?

**Comment by cg-cnu** [comment]
Hey @mrcolo go ahead with the issue 👍

**Comment by mrcolo** [comment]
Alright! On it!

**Comment by cg-cnu** [comment]
Hey guys! We have changed the design of the app from what's shown in the screenshot. So, this issue is no longer valid. Am sorry, I have to close this one for maintaining clarity in the issues. We will be creating more first-timers soon. Please feel free to pickup them once they are available. Thanks for your work on this one. 🙂
