### ISSUE TITLE
clean up `(` around single function parameters 

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/xplore#70]
## Expected Behavior

Arrow functions don't need to have a '(' around the parameters if its a single parameter.

## Current Behavior

Right now, some places we have '(', some places we don't have.

## Possible Solution

We can do a refactor to follow either of the style. @TalAter Let me know your thoughts! Can create few first timers with that!

**Comment by TalAter** [comment]
If there are still places where this is an issue, go ahead. I believe I fixed most earlier today.
