### ISSUE TITLE
🐛 truncate function in utils.js ignores the last character

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/xplore#73]
Thank you for your help ❤️

## What is this project?
DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Xplore
The DAV project you are looking at is Xplore. Xplore is a blockchain explorer you can run on your machine to explore local Ethereum nodes on your machine. It is used by developers working with DAV's libraries to ease development and see how the blockchain is affected by their work.

### The Issue
The task for this issue is to fix the bug in `truncate` function in `utils.js`.
Truncate function should return a shortened version of the text based on the `leadCharacterCount` and `trailCharacterCount` eg; `truncate('123456789', 2, 2)` should return `'12...89'`

The code in truncate function 

```javascript
text.substring(
      text.length - (trailingCharacterCount + 1),
      text.length - 1
    );
```
omits the last character because substring only returns the string until the n-th character (excluding it).

<img width="442" alt="xplore_utils_js_at_4e15ab50677717885d78c5a61a6ef5b5c475a277_ _cg-cnu_xplore" src="https://user-images.githubusercontent.com/926653/36629371-9ba73e00-195d-11e8-8ec5-f6c9427829e2.png">

As suggested by @TalAter using `slice` instead of `substring` - [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) solves this issue!

### Contributing to Xplore
- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ]  Comment in this issue that you would like to do it.
- [ ]  Open the Xplore GitHub page and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with $ git clone https://github.com/YOUR-GITHUB-USER-NAME/xplore.git
- [ ] Visit the [contributing guidelines](https://github.com/DAVFoundation/xplore/blob/master/CONTRIBUTING.md) for help getting started.
- [ ] Code, code, code...
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with $ git push -u origin master
- [ ] Visit your fork on GitHub.com (https://github.com/YOUR-USER-NAME/xplore) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: #5)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help
We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our gitter channel. We are always happy to help 😄

**Comment by ryan-barrett** [comment]
Hi, I'd like to work on this if I can.

**Comment by cg-cnu** [comment]
Hey @ryan-barrett Sure thing, go ahead 👍

**Comment by cg-cnu** [comment]
Awesome work @ryan-barrett 👏 Thanks!
