### ISSUE TITLE
TopBlocks is extremely confusing and should be renamed.

### ISSUE THREAD

**Issue by bicep** [DAVFoundation/xplore#82]
xplore is a block chain explorer, but the TopBlocks don't refer to a block on top of the blockchain- they refer to the the header row of information on the web app. This is extremely confusing and should be renamed. I am proposing something like HeaderBars or HeaderSections or something like that.

@TalAter @griffobeid What do you guys think?

**Comment by TalAter** [comment]
Good idea.

Go for it Roger!
